# Generated by Django 6.0 on 2025-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAppBE', '0002_cost_splited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='value',
            new_name='overall_value',
        ),
        migrations.AddField(
            model_name='splited',
            name='pay_back_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splited',
            name='split_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
