# Generated by Django 6.0 on 2025-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAppBE', '0004_splited_to_pay_back_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-05 21:38:37.851011'),
            preserve_default=False,
        ),
    ]
