# Generated by Django 6.0 on 2025-12-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAppBE', '0005_cost_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='payer',
        ),
        migrations.AddField(
            model_name='splited',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payed_splits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='splited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to=settings.AUTH_USER_MODEL),
        ),
    ]
