# Generated by Django 6.0 on 2025-12-26 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_currency', models.TextField(max_length=5)),
                ('trip_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_name', models.CharField(max_length=30)),
                ('overall_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=250)),
                ('payed_currency', models.TextField(max_length=5)),
                ('overall_value_main_currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripAppBE.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Join_code', models.CharField(db_index=True, max_length=8)),
                ('nickname', models.CharField(max_length=25)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tripAppBE.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Splited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.BooleanField(default=False)),
                ('split_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_pay_back_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_back_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_value_main_current', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('to_pay_back_value_main_current', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pay_back_value_main_current', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripAppBE.cost')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='tripAppBE.tripparticipant')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_splits', to='tripAppBE.tripparticipant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('trip', 'user'), name='unique_user_per_trip'),
        ),
    ]
