# Generated by Django 6.0 on 2025-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAppBE', '0003_rename_value_cost_overall_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splited',
            name='to_pay_back_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
