# Generated by Django 6.0 on 2025-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAppBE', '0006_remove_cost_payer_splited_payer_alter_splited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
